<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHjCMZxs\EccubeEccube_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHjCMZxs/EccubeEccube_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerHjCMZxs.legacy');

    return;
}

if (!\class_exists(EccubeEccube_KernelProdContainer::class, false)) {
    \class_alias(\ContainerHjCMZxs\EccubeEccube_KernelProdContainer::class, EccubeEccube_KernelProdContainer::class, false);
}

return new \ContainerHjCMZxs\EccubeEccube_KernelProdContainer([
    'container.build_hash' => 'HjCMZxs',
    'container.build_id' => '4a8b5be2',
    'container.build_time' => 1664809896,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHjCMZxs');
