<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.FyyT9V2' shared service.

return $this->privates['.service_locator.FyyT9V2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'pluginService' => ['services', 'Eccube\\Service\\PluginService', 'getPluginServiceService.php', true],
    'systemService' => ['services', 'Eccube\\Service\\SystemService', 'getSystemServiceService.php', true],
], [
    'pluginService' => 'Eccube\\Service\\PluginService',
    'systemService' => 'Eccube\\Service\\SystemService',
]);
