<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4xLvhZl' shared service.

return $this->privates['.service_locator.4xLvhZl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'systemService' => ['services', 'Eccube\\Service\\SystemService', 'getSystemServiceService.php', true],
], [
    'systemService' => 'Eccube\\Service\\SystemService',
]);
