<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.DjHglyl' shared service.

return $this->privates['.service_locator.DjHglyl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Customer' => ['privates', '.errored..service_locator.DjHglyl.Eccube\\Entity\\Customer', NULL, 'Cannot autowire service ".service_locator.DjHglyl": it references class "Eccube\\Entity\\Customer" but no such service exists.'],
], [
    'Customer' => 'Eccube\\Entity\\Customer',
]);
