<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7BeSyQ6' shared service.

return $this->privates['.service_locator.7BeSyQ6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cacheUtil' => ['privates', 'Eccube\\Util\\CacheUtil', 'getCacheUtilService.php', true],
    'fs' => ['services', 'filesystem', 'getFilesystemService.php', true],
    'twig' => ['services', 'twig', 'getTwigService', false],
], [
    'cacheUtil' => 'Eccube\\Util\\CacheUtil',
    'fs' => '?',
    'twig' => '?',
]);
