<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4HUlAmc' shared service.

return $this->privates['.service_locator.4HUlAmc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'shipping' => ['privates', '.errored..service_locator.4HUlAmc.Eccube\\Entity\\Shipping', NULL, 'Cannot autowire service ".service_locator.4HUlAmc": it references class "Eccube\\Entity\\Shipping" but no such service exists.'],
], [
    'shipping' => 'Eccube\\Entity\\Shipping',
]);
