<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.KS.Gc5o' shared service.

return $this->privates['.service_locator.KS.Gc5o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cartPurchaseFlow' => ['privates', 'eccube.purchase.flow.cart', 'getEccube_Purchase_Flow_CartService.php', true],
], [
    'cartPurchaseFlow' => '?',
]);
