<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.15S0unZ' shared service.

return $this->privates['.service_locator.15S0unZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ProductReview' => ['privates', '.errored..service_locator.15S0unZ.Plugin\\ProductReview4\\Entity\\ProductReview', NULL, 'Cannot autowire service ".service_locator.15S0unZ": it references class "Plugin\\ProductReview4\\Entity\\ProductReview" but no such service exists.'],
], [
    'ProductReview' => 'Plugin\\ProductReview4\\Entity\\ProductReview',
]);
