<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Nt8PxCc' shared service.

return $this->privates['.service_locator.Nt8PxCc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Template' => ['privates', '.errored..service_locator.Nt8PxCc.Eccube\\Entity\\Template', NULL, 'Cannot autowire service ".service_locator.Nt8PxCc": it references class "Eccube\\Entity\\Template" but no such service exists.'],
], [
    'Template' => 'Eccube\\Entity\\Template',
]);
