<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.CA2SJVg' shared service.

return $this->privates['.service_locator.CA2SJVg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Shipping' => ['privates', '.errored..service_locator.CA2SJVg.Eccube\\Entity\\Shipping', NULL, 'Cannot autowire service ".service_locator.CA2SJVg": it references class "Eccube\\Entity\\Shipping" but no such service exists.'],
], [
    'Shipping' => 'Eccube\\Entity\\Shipping',
]);
