<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.FuFaR2o' shared service.

return $this->privates['.service_locator.FuFaR2o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'News' => ['privates', '.errored..service_locator.FuFaR2o.Eccube\\Entity\\News', NULL, 'Cannot autowire service ".service_locator.FuFaR2o": it references class "Eccube\\Entity\\News" but no such service exists.'],
    'cacheUtil' => ['privates', 'Eccube\\Util\\CacheUtil', 'getCacheUtilService.php', true],
], [
    'News' => 'Eccube\\Entity\\News',
    'cacheUtil' => 'Eccube\\Util\\CacheUtil',
]);
