<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6ql.y7V' shared service.

return $this->privates['.service_locator.6ql.y7V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'em' => ['privates', '.errored..service_locator.6ql.y7V.Doctrine\\ORM\\EntityManager', NULL, 'Cannot autowire service ".service_locator.6ql.y7V": it references class "Doctrine\\ORM\\EntityManager" but no such service exists. Try changing the type-hint to "Doctrine\\ORM\\EntityManagerInterface" instead.'],
], [
    'em' => 'Doctrine\\ORM\\EntityManager',
]);
