<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.bXEDLRL' shared service.

return $this->privates['.service_locator.bXEDLRL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'RecommendProduct' => ['privates', '.errored..service_locator.bXEDLRL.Plugin\\Recommend4\\Entity\\RecommendProduct', NULL, 'Cannot autowire service ".service_locator.bXEDLRL": it references class "Plugin\\Recommend4\\Entity\\RecommendProduct" but no such service exists.'],
], [
    'RecommendProduct' => 'Plugin\\Recommend4\\Entity\\RecommendProduct',
]);
