<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.3PzBJ2J' shared service.

return $this->privates['.service_locator.3PzBJ2J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Layout' => ['privates', '.errored..service_locator.3PzBJ2J.Eccube\\Entity\\Layout', NULL, 'Cannot autowire service ".service_locator.3PzBJ2J": it references class "Eccube\\Entity\\Layout" but no such service exists.'],
    'cacheUtil' => ['privates', 'Eccube\\Util\\CacheUtil', 'getCacheUtilService.php', true],
], [
    'Layout' => 'Eccube\\Entity\\Layout',
    'cacheUtil' => 'Eccube\\Util\\CacheUtil',
]);
