<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qXw4ekQ' shared service.

return $this->privates['.service_locator.qXw4ekQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'extension' => ['privates', 'Eccube\\Twig\\Extension\\EccubeExtension', 'getEccubeExtensionService', false],
], [
    'extension' => 'Eccube\\Twig\\Extension\\EccubeExtension',
]);
