<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..UQPgt.' shared service.

return $this->privates['.service_locator..UQPgt.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Delivery' => ['privates', '.errored..service_locator..UQPgt..Eccube\\Entity\\Delivery', NULL, 'Cannot autowire service ".service_locator..UQPgt.": it references class "Eccube\\Entity\\Delivery" but no such service exists.'],
], [
    'Delivery' => 'Eccube\\Entity\\Delivery',
]);
