<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.unqMqV7' shared service.

return $this->privates['.service_locator.unqMqV7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ProductStatus' => ['privates', '.errored..service_locator.unqMqV7.Eccube\\Entity\\Master\\ProductStatus', NULL, 'Cannot autowire service ".service_locator.unqMqV7": it references class "Eccube\\Entity\\Master\\ProductStatus" but no such service exists.'],
    'cacheUtil' => ['privates', 'Eccube\\Util\\CacheUtil', 'getCacheUtilService.php', true],
], [
    'ProductStatus' => 'Eccube\\Entity\\Master\\ProductStatus',
    'cacheUtil' => 'Eccube\\Util\\CacheUtil',
]);
