<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.QQWarRh' shared service.

return $this->privates['.service_locator.QQWarRh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'TargetPayment' => ['privates', '.errored..service_locator.QQWarRh.Eccube\\Entity\\Payment', NULL, 'Cannot autowire service ".service_locator.QQWarRh": it references class "Eccube\\Entity\\Payment" but no such service exists.'],
], [
    'TargetPayment' => 'Eccube\\Entity\\Payment',
]);
