<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.iXGS5iD' shared service.

return $this->privates['.service_locator.iXGS5iD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Plugin' => ['privates', '.errored..service_locator.iXGS5iD.Eccube\\Entity\\Plugin', NULL, 'Cannot autowire service ".service_locator.iXGS5iD": it references class "Eccube\\Entity\\Plugin" but no such service exists.'],
], [
    'Plugin' => 'Eccube\\Entity\\Plugin',
]);
