<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tMnt6Yf' shared service.

return $this->privates['.service_locator.tMnt6Yf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'tokenManager' => ['services', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', false],
], [
    'tokenManager' => '?',
]);
