<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.TvMsdCu' shared service.

return $this->privates['.service_locator.TvMsdCu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'CsvType' => ['privates', '.errored..service_locator.TvMsdCu.Eccube\\Entity\\Master\\CsvType', NULL, 'Cannot autowire service ".service_locator.TvMsdCu": it references class "Eccube\\Entity\\Master\\CsvType" but no such service exists.'],
], [
    'CsvType' => 'Eccube\\Entity\\Master\\CsvType',
]);
