<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.akAX88H' shared service.

return $this->privates['.service_locator.akAX88H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'TaxRule' => ['privates', '.errored..service_locator.akAX88H.Eccube\\Entity\\TaxRule', NULL, 'Cannot autowire service ".service_locator.akAX88H": it references class "Eccube\\Entity\\TaxRule" but no such service exists.'],
], [
    'TaxRule' => 'Eccube\\Entity\\TaxRule',
]);
