<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.DlP8RSy' shared service.

return $this->privates['.service_locator.DlP8RSy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ClassName' => ['privates', '.errored..service_locator.DlP8RSy.Eccube\\Entity\\ClassName', NULL, 'Cannot autowire service ".service_locator.DlP8RSy": it references class "Eccube\\Entity\\ClassName" but no such service exists.'],
], [
    'ClassName' => 'Eccube\\Entity\\ClassName',
]);
