<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.WwAxeG6' shared service.

return $this->privates['.service_locator.WwAxeG6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Block' => ['privates', '.errored..service_locator.WwAxeG6.Eccube\\Entity\\Block', NULL, 'Cannot autowire service ".service_locator.WwAxeG6": it references class "Eccube\\Entity\\Block" but no such service exists.'],
    'cacheUtil' => ['privates', 'Eccube\\Util\\CacheUtil', 'getCacheUtilService.php', true],
    'fs' => ['services', 'filesystem', 'getFilesystemService.php', true],
], [
    'Block' => 'Eccube\\Entity\\Block',
    'cacheUtil' => 'Eccube\\Util\\CacheUtil',
    'fs' => '?',
]);
