<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.WwAxeG6.Eccube\Entity\Block' shared service.

$this->throw('Cannot autowire service ".service_locator.WwAxeG6": it references class "Eccube\\Entity\\Block" but no such service exists.');
