<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.DlP8RSy.Eccube\Entity\ClassName' shared service.

$this->throw('Cannot autowire service ".service_locator.DlP8RSy": it references class "Eccube\\Entity\\ClassName" but no such service exists.');
