<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Command\ComposerRequireAlreadyInstalledPluginsCommand' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ComposerRequireAlreadyInstalledPluginsCommand.php';

$this->privates['Eccube\\Command\\ComposerRequireAlreadyInstalledPluginsCommand'] = $instance = new \Eccube\Command\ComposerRequireAlreadyInstalledPluginsCommand(($this->services['Eccube\\Service\\Composer\\ComposerApiService'] ?? $this->load('getComposerApiServiceService.php')), ($this->services['Eccube\\Repository\\PluginRepository'] ?? $this->load('getPluginRepositoryService.php')), ($this->privates['Eccube\\Service\\PluginApiService'] ?? $this->load('getPluginApiServiceService.php')));

$instance->setName('eccube:composer:require-already-installed');

return $instance;
