<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Service\CsvExportService' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CsvExportService.php';

return $this->privates['Eccube\\Service\\CsvExportService'] = new \Eccube\Service\CsvExportService(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->privates['Eccube\\Repository\\CsvRepository'] ?? $this->load('getCsvRepositoryService.php')), ($this->privates['Eccube\\Repository\\Master\\CsvTypeRepository'] ?? $this->load('getCsvTypeRepositoryService.php')), ($this->privates['Eccube\\Repository\\OrderRepository'] ?? $this->getOrderRepositoryService()), ($this->privates['Eccube\\Repository\\ShippingRepository'] ?? $this->load('getShippingRepositoryService.php')), ($this->privates['Eccube\\Repository\\CustomerRepository'] ?? $this->load('getCustomerRepositoryService.php')), ($this->privates['Eccube\\Repository\\ProductRepository'] ?? $this->getProductRepositoryService()), ($this->services['Eccube\\Common\\EccubeConfig'] ?? ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))), ($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), ($this->services['knp_paginator'] ?? $this->load('getKnpPaginatorService.php')));
