<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\Coupon4\Service\CouponService' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'Coupon4'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CouponService.php';

return $this->privates['Plugin\\Coupon4\\Service\\CouponService'] = new \Plugin\Coupon4\Service\CouponService(($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService()), ($this->privates['Plugin\\Coupon4\\Repository\\CouponRepository'] ?? $this->load('getCouponRepositoryService.php')), ($this->privates['Plugin\\Coupon4\\Repository\\CouponOrderRepository'] ?? $this->load('getCouponOrderRepositoryService.php')), ($this->privates['Eccube\\Repository\\CategoryRepository'] ?? $this->load('getCategoryRepositoryService.php')), ($this->services['Eccube\\Service\\TaxRuleService'] ?? $this->load('getTaxRuleServiceService.php')), ($this->privates['Eccube\\Repository\\TaxRuleRepository'] ?? $this->getTaxRuleRepositoryService()), ($this->privates['Eccube\\Repository\\Master\\TaxTypeRepository'] ?? $this->load('getTaxTypeRepositoryService.php')), ($this->privates['Eccube\\Repository\\Master\\TaxDisplayTypeRepository'] ?? $this->load('getTaxDisplayTypeRepositoryService.php')), ($this->privates['Eccube\\Repository\\Master\\OrderItemTypeRepository'] ?? $this->load('getOrderItemTypeRepositoryService.php')), $this, ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->privates['Eccube\\Repository\\OrderItemRepository'] ?? $this->load('getOrderItemRepositoryService.php')), ($this->privates['Eccube\\Repository\\ProductClassRepository'] ?? $this->getProductClassRepositoryService()));
