<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.DjHglyl.Eccube\Entity\Customer' shared service.

$this->throw('Cannot autowire service ".service_locator.DjHglyl": it references class "Eccube\\Entity\\Customer" but no such service exists.');
