<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.6ublP36.Eccube\Entity\CustomerAddress' shared service.

$this->throw('Cannot autowire service ".service_locator.6ublP36": it references class "Eccube\\Entity\\CustomerAddress" but no such service exists.');
