<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.TvMsdCu.Eccube\Entity\Master\CsvType' shared service.

$this->throw('Cannot autowire service ".service_locator.TvMsdCu": it references class "Eccube\\Entity\\Master\\CsvType" but no such service exists.');
