<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Eccube\Service\Payment\Method\Cash' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Payment'.\DIRECTORY_SEPARATOR.'PaymentMethodInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Payment'.\DIRECTORY_SEPARATOR.'Method'.\DIRECTORY_SEPARATOR.'Cash.php';

return $this->services['Eccube\\Service\\Payment\\Method\\Cash'] = new \Eccube\Service\Payment\Method\Cash(($this->services['eccube.purchase.flow.shopping'] ?? $this->load('getEccube_Purchase_Flow_ShoppingService.php')));
