<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\MailMagazine4\Repository\MailMagazineTemplateRepository' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'MailMagazine4'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'MailMagazineTemplateRepository.php';

return $this->privates['Plugin\\MailMagazine4\\Repository\\MailMagazineTemplateRepository'] = new \Plugin\MailMagazine4\Repository\MailMagazineTemplateRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
