<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\MailMagazine4\Event\MailMagazineHistoryFilePaginationSubscriber' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'MailMagazine4'.\DIRECTORY_SEPARATOR.'Event'.\DIRECTORY_SEPARATOR.'MailMagazineHistoryFilePaginationSubscriber.php';

return $this->privates['Plugin\\MailMagazine4\\Event\\MailMagazineHistoryFilePaginationSubscriber'] = new \Plugin\MailMagazine4\Event\MailMagazineHistoryFilePaginationSubscriber(($this->privates['Plugin\\MailMagazine4\\Service\\MailMagazineService'] ?? $this->load('getMailMagazineServiceService.php')));
