<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\MailMagazine4\Repository\MailMagazineSendHistoryRepository' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'MailMagazine4'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'MailMagazineSendHistoryRepository.php';

return $this->privates['Plugin\\MailMagazine4\\Repository\\MailMagazineSendHistoryRepository'] = new \Plugin\MailMagazine4\Repository\MailMagazineSendHistoryRepository(($this->privates['Eccube\\Doctrine\\Query\\Queries'] ?? $this->getQueriesService()), ($this->services['doctrine'] ?? $this->getDoctrineService()));
