<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.Aihl1ZV.Plugin\MailMagazine4\Entity\MailMagazineTemplate' shared service.

$this->throw('Cannot autowire service ".service_locator.Aihl1ZV": it references class "Plugin\\MailMagazine4\\Entity\\MailMagazineTemplate" but no such service exists.');
