<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.CPu1jZD.Plugin\MailMagazine4\Entity\MailMagazineSendHistory' shared service.

$this->throw('Cannot autowire service ".service_locator.CPu1jZD": it references class "Plugin\\MailMagazine4\\Entity\\MailMagazineSendHistory" but no such service exists.');
