<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Service\OrderPdfService' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'tecnickcom'.\DIRECTORY_SEPARATOR.'tcpdf'.\DIRECTORY_SEPARATOR.'tcpdf.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'setasign'.\DIRECTORY_SEPARATOR.'fpdi'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'FpdiTrait.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'setasign'.\DIRECTORY_SEPARATOR.'fpdi'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Tcpdf'.\DIRECTORY_SEPARATOR.'Fpdi.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'setasign'.\DIRECTORY_SEPARATOR.'fpdi'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'TcpdfFpdi.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Eccube'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'OrderPdfService.php';

return $this->privates['Eccube\\Service\\OrderPdfService'] = new \Eccube\Service\OrderPdfService(($this->services['Eccube\\Common\\EccubeConfig'] ?? ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))), ($this->privates['Eccube\\Repository\\OrderRepository'] ?? $this->getOrderRepositoryService()), ($this->privates['Eccube\\Repository\\ShippingRepository'] ?? $this->load('getShippingRepositoryService.php')), ($this->services['Eccube\\Service\\TaxRuleService'] ?? $this->load('getTaxRuleServiceService.php')), ($this->privates['Eccube\\Repository\\BaseInfoRepository'] ?? $this->getBaseInfoRepositoryService()), ($this->privates['Eccube\\Twig\\Extension\\EccubeExtension'] ?? $this->getEccubeExtensionService()), ($this->privates['Eccube\\Twig\\Extension\\TaxExtension'] ?? $this->getTaxExtensionService()));
