<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.gFBlZjv.Eccube\Entity\Order' shared service.

$this->throw('Cannot autowire service ".service_locator.gFBlZjv": it references class "Eccube\\Entity\\Order" but no such service exists.');
