<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator._Z34Oca.Eccube\Entity\Product' shared service.

$this->throw('Cannot autowire service ".service_locator._Z34Oca": it references class "Eccube\\Entity\\Product" but no such service exists.');
