<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.unqMqV7.Eccube\Entity\Master\ProductStatus' shared service.

$this->throw('Cannot autowire service ".service_locator.unqMqV7": it references class "Eccube\\Entity\\Master\\ProductStatus" but no such service exists.');
