<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.jIkrOw2.Eccube\Entity\Plugin' shared service.

$this->throw('Cannot autowire service ".service_locator.jIkrOw2": it references class "Eccube\\Entity\\Plugin" but no such service exists.');
