<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\RelatedProduct4\Repository\RelatedProductRepository' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'RelatedProduct4'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'RelatedProductRepository.php';

return $this->privates['Plugin\\RelatedProduct4\\Repository\\RelatedProductRepository'] = new \Plugin\RelatedProduct4\Repository\RelatedProductRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
