<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\Api\GraphQL\Schema' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'webonyx'.\DIRECTORY_SEPARATOR.'graphql-php'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'Schema.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'GraphQL'.\DIRECTORY_SEPARATOR.'Schema.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'GraphQL'.\DIRECTORY_SEPARATOR.'Query.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'GraphQL'.\DIRECTORY_SEPARATOR.'Query'.\DIRECTORY_SEPARATOR.'SingleResultQuery.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'GraphQL'.\DIRECTORY_SEPARATOR.'Query'.\DIRECTORY_SEPARATOR.'CustomerQuery.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'GraphQL'.\DIRECTORY_SEPARATOR.'Query'.\DIRECTORY_SEPARATOR.'SearchFormQuery.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'GraphQL'.\DIRECTORY_SEPARATOR.'Query'.\DIRECTORY_SEPARATOR.'CustomersQuery.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'GraphQL'.\DIRECTORY_SEPARATOR.'Query'.\DIRECTORY_SEPARATOR.'OrderQuery.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'GraphQL'.\DIRECTORY_SEPARATOR.'Query'.\DIRECTORY_SEPARATOR.'OrdersQuery.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'GraphQL'.\DIRECTORY_SEPARATOR.'Query'.\DIRECTORY_SEPARATOR.'ProductQuery.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'GraphQL'.\DIRECTORY_SEPARATOR.'Query'.\DIRECTORY_SEPARATOR.'ProductsQuery.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'GMC'.\DIRECTORY_SEPARATOR.'GraphQL'.\DIRECTORY_SEPARATOR.'DeliveryQuery.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'GraphQL'.\DIRECTORY_SEPARATOR.'Mutation.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'GraphQL'.\DIRECTORY_SEPARATOR.'Mutation'.\DIRECTORY_SEPARATOR.'UpdateProductStockMutation.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'GraphQL'.\DIRECTORY_SEPARATOR.'Mutation'.\DIRECTORY_SEPARATOR.'UpdateShippedMutation.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'GMC'.\DIRECTORY_SEPARATOR.'GraphQL'.\DIRECTORY_SEPARATOR.'SiteVerifyMutation.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'GMC'.\DIRECTORY_SEPARATOR.'GraphQL'.\DIRECTORY_SEPARATOR.'WebHookMutation.php';

$a = ($this->privates['Plugin\\Api\\GraphQL\\Types'] ?? $this->load('getTypesService.php'));
$b = new \ArrayObject();

$c = new \Plugin\Api\GraphQL\Query\CustomerQuery();

$d = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService());

$c->setEntityManager($d);
$c->setTypes($a);
$e = new \Plugin\Api\GraphQL\Query\CustomersQuery(($this->privates['Eccube\\Repository\\CustomerRepository'] ?? $this->load('getCustomerRepositoryService.php')));

$f = ($this->services['knp_paginator'] ?? $this->load('getKnpPaginatorService.php'));
$g = ($this->services['Eccube\\Common\\EccubeConfig'] ?? ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this)));
$h = ($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php'));

$e->setPaginator($f);
$e->setEccubeConfig($g);
$e->setFormFactory($h);
$e->setTypes($a);
$i = new \Plugin\Api\GraphQL\Query\OrderQuery();
$i->setEntityManager($d);
$i->setTypes($a);
$j = new \Plugin\Api\GraphQL\Query\OrdersQuery(($this->privates['Eccube\\Repository\\OrderRepository'] ?? $this->getOrderRepositoryService()));
$j->setPaginator($f);
$j->setEccubeConfig($g);
$j->setFormFactory($h);
$j->setTypes($a);
$k = new \Plugin\Api\GraphQL\Query\ProductQuery();
$k->setEntityManager($d);
$k->setTypes($a);
$l = new \Plugin\Api\GraphQL\Query\ProductsQuery(($this->privates['Eccube\\Repository\\ProductRepository'] ?? $this->getProductRepositoryService()));
$l->setPaginator($f);
$l->setEccubeConfig($g);
$l->setFormFactory($h);
$l->setTypes($a);

$b->append($c);
$b->append($e);
$b->append($i);
$b->append($j);
$b->append($k);
$b->append($l);
$b->append(new \Plugin\GMC\GraphQL\DeliveryQuery($a, ($this->privates['Eccube\\Repository\\DeliveryRepository'] ?? $this->load('getDeliveryRepositoryService.php'))));
$m = new \ArrayObject();
$m->append(new \Plugin\Api\GraphQL\Mutation\UpdateProductStockMutation($a, ($this->privates['Eccube\\Repository\\ProductClassRepository'] ?? $this->getProductClassRepositoryService()), $d));
$m->append(new \Plugin\Api\GraphQL\Mutation\UpdateShippedMutation($g, $d, ($this->privates['Eccube\\Service\\MailService'] ?? $this->load('getMailServiceService.php')), ($this->privates['Eccube\\Service\\OrderStateMachine'] ?? $this->load('getOrderStateMachineService.php')), ($this->privates['Eccube\\Repository\\Master\\OrderStatusRepository'] ?? $this->load('getOrderStatusRepositoryService.php')), $a, ($this->privates['Eccube\\Repository\\ShippingRepository'] ?? $this->load('getShippingRepositoryService.php'))));
$m->append(new \Plugin\GMC\GraphQL\SiteVerifyMutation($g));
$m->append(new \Plugin\GMC\GraphQL\WebHookMutation(($this->privates['Plugin\\Api\\Repository\\WebHookRepository'] ?? $this->getWebHookRepositoryService()), $d, $g));

return $this->privates['Plugin\\Api\\GraphQL\\Schema'] = new \Plugin\Api\GraphQL\Schema($a, $b, $m);
