<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.listener.oauth2.api' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security'.\DIRECTORY_SEPARATOR.'Http'.\DIRECTORY_SEPARATOR.'Firewall'.\DIRECTORY_SEPARATOR.'ListenerInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'trikoder'.\DIRECTORY_SEPARATOR.'oauth2-bundle'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'Firewall'.\DIRECTORY_SEPARATOR.'OAuth2Listener.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'trikoder'.\DIRECTORY_SEPARATOR.'oauth2-bundle'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'Authentication'.\DIRECTORY_SEPARATOR.'Token'.\DIRECTORY_SEPARATOR.'OAuth2TokenFactory.php';

return $this->privates['security.authentication.listener.oauth2.api'] = new \Trikoder\Bundle\OAuth2Bundle\Security\Firewall\OAuth2Listener(($this->services['security.token_storage'] ?? $this->getSecurity_TokenStorageService()), ($this->privates['security.authentication.manager'] ?? $this->getSecurity_Authentication_ManagerService()), ($this->privates['sensio_framework_extra.psr7.http_message_factory'] ?? $this->load('getSensioFrameworkExtra_Psr7_HttpMessageFactoryService.php')), ($this->privates['Trikoder\\Bundle\\OAuth2Bundle\\Security\\Authentication\\Token\\OAuth2TokenFactory'] ?? ($this->privates['Trikoder\\Bundle\\OAuth2Bundle\\Security\\Authentication\\Token\\OAuth2TokenFactory'] = new \Trikoder\Bundle\OAuth2Bundle\Security\Authentication\Token\OAuth2TokenFactory('ROLE_OAUTH2_'))), 'api');
