<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.CA2SJVg.Eccube\Entity\Shipping' shared service.

$this->throw('Cannot autowire service ".service_locator.CA2SJVg": it references class "Eccube\\Entity\\Shipping" but no such service exists.');
