<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.tU8XB4g.Psr\Http\Message\ServerRequestInterface' shared service.

$this->throw('Cannot autowire service ".service_locator.tU8XB4g": it references interface "Psr\\Http\\Message\\ServerRequestInterface" but no such service exists. Did you create a class that implements this interface?');
