<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.akAX88H.Eccube\Entity\TaxRule' shared service.

$this->throw('Cannot autowire service ".service_locator.akAX88H": it references class "Eccube\\Entity\\TaxRule" but no such service exists.');
