<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.i6NmKdJ.Plugin\Api\Entity\WebHook' shared service.

$this->throw('Cannot autowire service ".service_locator.i6NmKdJ": it references class "Plugin\\Api\\Entity\\WebHook" but no such service exists.');
